### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by plarrea** [ZaninAndrea/react-draggable-tabs#1]
I get this error when moving tabs, is there a workaround? I'm using react and react-dom ^16.1.1

**Comment by shd101wyy** [comment]
I am having the same problem. Anyone knows how to get it work?

**Comment by plarrea** [comment]
I'm using this fork https://github.com/AnnPin/react-draggable-tabs as a workaround

**Comment by shd101wyy** [comment]
Thanks @plarrea , problem solved.
